### ISSUE TITLE
Single Matsushita/Panasonic CR56x CD-ROM driver for Linux

### ISSUE THREAD

**Issue by chrisblown** [Fastdruid/CDTVPiDrive#1]
Hi, came across this on CDTVLand Discord. I have been collecting info on these CDTV drives for a year or more, also reading the code in UAE (cdtv.cpp). I came across this (attached) which might be of interest (seems to no longer be online) - Single Matsushita/Panasonic CR56x CD-ROM driver for Linux. I believe these are more or less the same drives as the CDTV... (?).
Also keen to assist in any way for the project. 
Chris
[pcd.zip](https://github.com/user-attachments/files/18006385/pcd.zip)

**Comment by Fastdruid** [comment]
Thanks Chris. I've got a copy of that already but they are utterly, utterly different! 

It appears that Matsushita basically tweaked it for every implementation, while the "syntax" is broadly comparable the CDTV (and presumably the A570 too) has commands and responses that are totally different. I've been chatting with C4ptFuture regarding this and I think I've got the full command set.

**Comment by chrisblown** [comment]
Yes its a unicorn alright.. great news on the command set. I can see on the PCB you have CN3, so you plan to support digital cd audio? Maybe ask C4ptFuture to add a Discord channel to CDTVLand for this project. Again happy to support this project in any way I can. Its something that I've been thinking about (and pestering C4pt about for sometime) yet haven't had the time (and skill) to do anything about it :)

**Comment by Fastdruid** [comment]
All audio is digital from the drive. 

CN3 itself isn't digital audio. It's bidirectional I2C that allows control of audio from the LC6554H. It both receives track info from the drive as well as tells the drive to play. 

... I should probably put the breakdown and description of the signals in this repo (they're in the ReCDTV repo).

Anyway, feel free to ask, C4pt has my email and I'll come join!

**Comment by chrisblown** [comment]
Ah yes that's right, since you can control the cd drive independant from the OS via the front buttons. C4pt did mentioned this will add extra complexity to creating an optical drive emulator..

**Comment by Fastdruid** [comment]
Not overly difficult tbh the RPi will play PCM over I2S so if you're splitting the CD into data ISO and music tracks then its merely a case of "playing" the music file.

**Comment by chrisblown** [comment]
Woah! - I just found those details you mentioned in ReCDTV..  would be great to add them (link them) here..
